
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from 'react';
import Link from 'next/link';

import { UserIcon, ClipboardDocumentListIcon, PencilSquareIcon, CheckBadgeIcon, HomeIcon } from '@heroicons/react/24/outline';
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const navItems = [
  { href: '/', icon: <HomeIcon className="w-6 h-6" />, label: 'Dashboard' },
  { href: '/alunos', icon: <UserIcon className="w-6 h-6" />, label: 'Alunos' },
  { href: '/treinos', icon: <ClipboardDocumentListIcon className="w-6 h-6" />, label: 'Treinos' },
  { href: '/matriculas', icon: <PencilSquareIcon className="w-6 h-6" />, label: 'Matrículas' },
  { href: '/frequencias', icon: <CheckBadgeIcon className="w-6 h-6" />, label: 'Frequências' },
];


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`bg-gradient-to-br from-zinc-950 via-zinc-900 to-zinc-800 min-h-screen font-sans ${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main className="pt-20 p-8 max-w-7xl mx-auto w-full min-h-[calc(100vh-80px)]">{children}</main>
      </body>
    </html>
  );
}
